# Generated by Django 2.0 on 2019-01-31 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_height', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('zoom_diameter', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('focus_height', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('focus_diameter', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_plunge_distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('medium_plunge_distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('large_plunge_distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cnc_is_locked', models.BooleanField(default=False)),
                ('recent_orders_to_retain', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StandardBandit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='lense',
            name='custom_band_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.StandardBandit'),
        ),
    ]
