# Generated by Django 2.0 on 2019-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('diameter', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('type', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_plunge_distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('medium_plunge_distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('large_plunge_distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cnc_is_locked', models.BooleanField(default=False)),
                ('recent_orders_to_retain', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StandardBandit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('initial_height', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
