# Generated by Django 2.0 on 2019-02-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190221_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='lense',
            name='amount_processed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
