# Generated by Django 2.0 on 2019-02-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190202_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lense',
            name='custom_band_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.StandardBandit'),
        ),
    ]
