# Generated by Django 2.0 on 2019-02-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190202_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lense',
            name='custom_band_size',
        ),
        migrations.AddField(
            model_name='lense',
            name='custom_focus_band_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_focus_band_size', to='management.StandardBandit'),
        ),
        migrations.AddField(
            model_name='lense',
            name='custom_zoom_band_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_zoom_band_size', to='management.StandardBandit'),
        ),
    ]
