# Generated by Django 2.0 on 2019-02-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_savedqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedqueue',
            name='name',
            field=models.CharField(default='MAGA', max_length=100),
            preserve_default=False,
        ),
    ]
