# Generated by Django 2.0 on 2019-02-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_lense_amount_processed'),
        ('website', '0003_savedqueue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Lense')),
            ],
        ),
        migrations.RemoveField(
            model_name='savedqueue',
            name='lenses',
        ),
        migrations.AddField(
            model_name='savedqueueitem',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SavedQueue'),
        ),
    ]
