# Generated by Django 2.0 on 2019-02-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_processed', models.PositiveIntegerField(default=0)),
                ('lense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Lense')),
            ],
        ),
        migrations.CreateModel(
            name='RecentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenses', models.ManyToManyField(to='management.Lense')),
            ],
        ),
    ]
