# Generated by Django 2.0 on 2019-02-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='lense',
        ),
        migrations.RemoveField(
            model_name='recentorder',
            name='lenses',
        ),
        migrations.DeleteModel(
            name='Diagnostic',
        ),
        migrations.DeleteModel(
            name='RecentOrder',
        ),
    ]
