# Generated by Django 2.0 on 2019-02-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='amount_processed',
            new_name='amount_focus_processed',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='amount_zoom_processed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
